/**
 * Created by lichun on 2017/3/31.
 */
export const AWESOME_PREDICT = 'AWESOME_PREDICT';
export const AWESOME_PREDICT_EXPECT = 'AWESOME_PREDICT_EXPECT';
export const COLDHOT_DISTRIBUTE = 'COLDHOT_DISTRIBUTE';
export const STRENGTH_COMPARE = 'STRENGTH_COMPARE';
export const COMBAT_FEATURE = 'COMBAT_FEATURE';
